spring:
  application:
    name: Warehouse-Workshop

  logging:
    level:
      org.hibernate.SQL: INFO
      org.hibernate.orm.jdbc.bind: INFO

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password